[project]
name = "microsoft-kb-metadata"
version = "0.1.0"
description = "Generate Microsoft Knowledge Base metadata mappings"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "html5lib>=1.1",
    "requests>=2.32.3",
]

