[project]
name = "microsoft-kb-metadata"
version = "0.1.1"
description = "Generate Microsoft Knowledge Base metadata mappings"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "html5lib>=1.1",
    "requests>=2.32.3",
]

