name: Publish Dataset
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install csvs-to-sqlite
        run: pipx install sqlite-utils
      - name: Convert JSON to CSV
        run: jq -r '"kb,date,url,slug,uuid", keys[] as $k |  [$k]  + [  .[$k].date, .[$k].url, .[$k].slug, .[$k].uuid  ]|@csv' data.json > data.csv
      - name: Convert CSV to SQLite
        run: sqlite-utils insert data.db data data.csv --csv
      - name: Create and publish tag and release
        run: |
          TAG_NAME=v$(date +'%Y.%m.%d')
          git tag $TAG_NAME
          git push origin $TAG_NAME
          gh release create $TAG_NAME data.json data.csv data.db --title "Release $TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}