name: Publish Dataset
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install csvs-to-sqlite
        run: pip install csvs-to-sqlite
      - name: Convert JSON to CSV
        run: jq -r '"kb,date,url,slug,uuid", keys[] as $k |  [$k]  + [  .[$k].date, .[$k].url, .[$k].slug, .[$k].uuid  ]|@csv' data.json > data.csv
      - name: Convert CSV to SQLite
        run: csvs-to-sqlite --table data --date date data.csv data.db
      - name: Create and push tag
        run: |
          TAG_NAME=v$(date +'%Y.%m.%d')
          git tag $TAG_NAME
          git push origin $TAG_NAME
      - name: Publish files to GitHub Releases
        run: gh release create $TAG_NAME data.json data.csv data.db --title "Release $TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}