name: Update Data
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '7 18 * * *'
jobs:
  update:
    permissions:
      contents: write
      packages: write
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install
    - name: Update data
      run: |
        uv sync --all-extras --dev
        uv run update.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update KB Data
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: "data.json"